package main

import (
	"fmt"
	"strings"
	"unicode"
)

// PatternInfo holds extracted metadata about a single query pattern.
type PatternInfo struct {
	// RootNodeType is the top-level node type of the pattern (e.g., "function_declaration").
	RootNodeType string
	// Captures maps capture name to whether it can match multiple nodes.
	Captures []CaptureInfo
}

// CaptureInfo describes a single capture in a pattern.
type CaptureInfo struct {
	Name       string // original capture name (e.g., "name", "function.name")
	IsMultiple bool   // true if inside * or + quantifier
}

// Generate produces Go source code for a typed query wrapper.
func Generate(querySource, typeName, packageName, langName string) (string, error) {
	patterns, err := extractPatterns(querySource)
	if err != nil {
		return "", err
	}

	if len(patterns) == 0 {
		return "", fmt.Errorf("no patterns found in query")
	}

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "// Code generated by tsquery; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import gotreesitter \"github.com/odvcencio/gotreesitter\"\n\n")

	// Generate match structs for each pattern.
	structNames := make([]string, len(patterns))
	usedNames := make(map[string]int)
	for i, p := range patterns {
		structName := patternStructName(p, i, typeName, usedNames)
		structNames[i] = structName

		fmt.Fprintf(&b, "// %s is a typed match for pattern %d", structName, i)
		if p.RootNodeType != "" {
			fmt.Fprintf(&b, " (%s)", p.RootNodeType)
		}
		fmt.Fprintf(&b, ".\n")
		fmt.Fprintf(&b, "type %s struct {\n", structName)
		for _, cap := range p.Captures {
			fieldName := captureToFieldName(cap.Name)
			if cap.IsMultiple {
				fmt.Fprintf(&b, "\t%s []*gotreesitter.Node\n", fieldName)
			} else {
				fmt.Fprintf(&b, "\t%s *gotreesitter.Node\n", fieldName)
			}
		}
		fmt.Fprintf(&b, "}\n\n")
	}

	// Query type.
	fmt.Fprintf(&b, "// %sQuery holds the compiled query.\n", typeName)
	fmt.Fprintf(&b, "type %sQuery struct {\n", typeName)
	fmt.Fprintf(&b, "\tq *gotreesitter.Query\n")
	fmt.Fprintf(&b, "}\n\n")

	// Constructor.
	fmt.Fprintf(&b, "// New%sQuery compiles the query against the given language.\n", typeName)
	fmt.Fprintf(&b, "func New%sQuery(lang *gotreesitter.Language) (*%sQuery, error) {\n", typeName, typeName)
	fmt.Fprintf(&b, "\tq, err := gotreesitter.NewQuery(%s, lang)\n", goStringLiteral(querySource))
	fmt.Fprintf(&b, "\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn nil, err\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn &%sQuery{q: q}, nil\n", typeName)
	fmt.Fprintf(&b, "}\n\n")

	// Cursor type.
	fmt.Fprintf(&b, "// %sQueryCursor iterates over typed matches.\n", typeName)
	fmt.Fprintf(&b, "type %sQueryCursor struct {\n", typeName)
	fmt.Fprintf(&b, "\tcursor *gotreesitter.QueryCursor\n")
	fmt.Fprintf(&b, "\tquery  *gotreesitter.Query\n")
	fmt.Fprintf(&b, "}\n\n")

	// Exec method.
	fmt.Fprintf(&b, "// Exec returns a cursor that yields typed matches.\n")
	fmt.Fprintf(&b, "func (q *%sQuery) Exec(node *gotreesitter.Node, lang *gotreesitter.Language, source []byte) *%sQueryCursor {\n", typeName, typeName)
	fmt.Fprintf(&b, "\treturn &%sQueryCursor{\n", typeName)
	fmt.Fprintf(&b, "\t\tcursor: q.q.Exec(node, lang, source),\n")
	fmt.Fprintf(&b, "\t\tquery:  q.q,\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n\n")

	if len(patterns) == 1 {
		// Single-pattern: Next returns the typed struct directly.
		p := patterns[0]
		sn := structNames[0]

		fmt.Fprintf(&b, "// Next returns the next typed match, or false when done.\n")
		fmt.Fprintf(&b, "func (c *%sQueryCursor) Next() (%s, bool) {\n", typeName, sn)
		fmt.Fprintf(&b, "\tm, ok := c.cursor.NextMatch()\n")
		fmt.Fprintf(&b, "\tif !ok {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, false\n", sn)
		fmt.Fprintf(&b, "\t}\n")
		fmt.Fprintf(&b, "\tvar result %s\n", sn)
		emitCaptureAssignments(&b, p, "\t")
		fmt.Fprintf(&b, "\treturn result, true\n")
		fmt.Fprintf(&b, "}\n")
	} else {
		// Multi-pattern: Next returns pattern index and typed struct.
		// We generate a NextPatternN method for each pattern.
		fmt.Fprintf(&b, "// Next returns the pattern index and raw match. Use the pattern-specific\n")
		fmt.Fprintf(&b, "// methods to convert to typed structs.\n")
		fmt.Fprintf(&b, "func (c *%sQueryCursor) Next() (gotreesitter.QueryMatch, bool) {\n", typeName)
		fmt.Fprintf(&b, "\treturn c.cursor.NextMatch()\n")
		fmt.Fprintf(&b, "}\n\n")

		for i, p := range patterns {
			sn := structNames[i]
			fmt.Fprintf(&b, "// MatchPattern%d converts a raw match (pattern %d) into a %s.\n", i, i, sn)
			fmt.Fprintf(&b, "func MatchPattern%d(m gotreesitter.QueryMatch) %s {\n", i, sn)
			fmt.Fprintf(&b, "\tvar result %s\n", sn)
			emitCaptureAssignments(&b, p, "\t")
			fmt.Fprintf(&b, "\treturn result\n")
			fmt.Fprintf(&b, "}\n\n")
		}
	}

	return b.String(), nil
}

// emitCaptureAssignments writes the capture-to-field assignment code.
func emitCaptureAssignments(b *strings.Builder, p PatternInfo, indent string) {
	fmt.Fprintf(b, "%sfor _, cap := range m.Captures {\n", indent)
	fmt.Fprintf(b, "%s\tswitch cap.Name {\n", indent)
	for _, cap := range p.Captures {
		fieldName := captureToFieldName(cap.Name)
		fmt.Fprintf(b, "%s\tcase %q:\n", indent, cap.Name)
		if cap.IsMultiple {
			fmt.Fprintf(b, "%s\t\tresult.%s = append(result.%s, cap.Node)\n", indent, fieldName, fieldName)
		} else {
			fmt.Fprintf(b, "%s\t\tresult.%s = cap.Node\n", indent, fieldName)
		}
	}
	fmt.Fprintf(b, "%s\t}\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

// extractPatterns does a lightweight parse of the .scm query source to
// extract pattern root node types and capture names. This is not a full
// S-expression parser — it extracts just enough to generate typed wrappers.
func extractPatterns(source string) ([]PatternInfo, error) {
	var patterns []PatternInfo
	i := 0
	for i < len(source) {
		// Skip whitespace and comments.
		for i < len(source) && (source[i] == ' ' || source[i] == '\t' || source[i] == '\n' || source[i] == '\r') {
			i++
		}
		if i >= len(source) {
			break
		}
		// Skip line comments.
		if source[i] == ';' {
			for i < len(source) && source[i] != '\n' {
				i++
			}
			continue
		}

		if source[i] == '(' || source[i] == '[' {
			p, newI, err := parsePattern(source, i)
			if err != nil {
				return nil, err
			}
			patterns = append(patterns, p)
			i = newI
		} else if source[i] == '"' {
			// String pattern — skip it.
			_, newI, err := skipString(source, i)
			if err != nil {
				return nil, err
			}
			// Collect any captures after the string.
			p := PatternInfo{RootNodeType: "string_literal"}
			newI, p.Captures = collectCaptures(source, newI)
			patterns = append(patterns, p)
			i = newI
		} else {
			// Skip unknown tokens.
			i++
		}
	}
	return patterns, nil
}

// parsePattern parses a single top-level pattern starting at pos.
func parsePattern(source string, pos int) (PatternInfo, int, error) {
	p := PatternInfo{}
	depth := 0
	i := pos

	// Track if we're looking for the root node type.
	foundRoot := false
	inQuantifier := false

	for i < len(source) {
		ch := source[i]

		switch {
		case ch == '(' || ch == '[':
			depth++
			i++
			// After the opening paren, the next identifier is a node type.
			// Only capture the root (depth == 1) node type.
			if depth == 1 && !foundRoot {
				j := skipWS(source, i)
				if j < len(source) && isIdentStart(source[j]) {
					end := j
					for end < len(source) && isIdentChar(source[end]) {
						end++
					}
					p.RootNodeType = source[j:end]
					foundRoot = true
				}
			}

		case ch == ')' || ch == ']':
			depth--
			inQuantifier = false
			i++
			if depth == 0 {
				// Collect captures after the closing paren and merge with existing.
				var trailing []CaptureInfo
				i, trailing = collectCaptures(source, i)
				for _, c := range trailing {
					p.Captures = addCapture(p.Captures, c.Name, c.IsMultiple)
				}
				// Skip any trailing predicates at depth 0.
				i = skipPredicates(source, i)
				return p, i, nil
			}

		case ch == '@':
			// Capture — extract name.
			i++
			start := i
			for i < len(source) && isIdentChar(source[i]) {
				i++
			}
			name := source[start:i]
			if name != "_" && name != "" {
				p.Captures = addCapture(p.Captures, name, inQuantifier)
			}
			inQuantifier = false // quantifier applies to one capture

		case ch == '*' || ch == '+':
			inQuantifier = true
			i++

		case ch == '?':
			i++

		case ch == '#':
			// Predicate — skip to matching ')', respecting strings and nesting.
			// The opening '(' was already processed above (depth++), so we
			// track our own predicate depth and decrement the outer depth.
			pDepth := 1
			for i < len(source) && pDepth > 0 {
				if source[i] == '"' {
					_, newI, _ := skipString(source, i)
					i = newI
					continue
				}
				if source[i] == '(' {
					pDepth++
				} else if source[i] == ')' {
					pDepth--
				}
				i++
			}
			depth-- // undo the depth++ from the '(' that preceded '#'

		case ch == '"':
			// String — skip.
			_, newI, err := skipString(source, i)
			if err != nil {
				return p, i, err
			}
			i = newI

		case ch == ';':
			// Comment — skip to end of line.
			for i < len(source) && source[i] != '\n' {
				i++
			}

		case ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r':
			i++

		case ch == '.':
			i++ // anchor

		case ch == ':':
			// Field name — skip.
			i++
			for i < len(source) && (source[i] == ' ' || source[i] == '\t') {
				i++
			}

		case ch == '_':
			// Wildcard node — skip.
			i++

		default:
			// Identifier or other token.
			for i < len(source) && isIdentChar(source[i]) {
				i++
			}
		}
	}

	if depth > 0 {
		return p, i, fmt.Errorf("unclosed parenthesis in pattern starting at position %d", pos)
	}

	return p, i, nil
}

func addCapture(captures []CaptureInfo, name string, isMultiple bool) []CaptureInfo {
	// Check if already exists.
	for i, c := range captures {
		if c.Name == name {
			if isMultiple {
				captures[i].IsMultiple = true
			}
			return captures
		}
	}
	return append(captures, CaptureInfo{Name: name, IsMultiple: isMultiple})
}

func collectCaptures(source string, pos int) (int, []CaptureInfo) {
	var captures []CaptureInfo
	i := pos
	for {
		i = skipWS(source, i)
		if i >= len(source) || source[i] != '@' {
			break
		}
		i++ // skip '@'
		start := i
		for i < len(source) && isIdentChar(source[i]) {
			i++
		}
		name := source[start:i]
		if name != "_" && name != "" {
			captures = addCapture(captures, name, false)
		}
	}
	return i, captures
}

func skipPredicates(source string, pos int) int {
	i := pos
	for {
		i = skipWS(source, i)
		// Skip line comments.
		for i < len(source) && source[i] == ';' {
			for i < len(source) && source[i] != '\n' {
				i++
			}
			i = skipWS(source, i)
		}
		if i >= len(source) || source[i] != '(' {
			break
		}
		// Check if this looks like a predicate: (#...
		j := i + 1
		j = skipWS(source, j)
		if j < len(source) && source[j] == '#' {
			// Skip the predicate.
			depth := 1
			i = i + 1
			for i < len(source) && depth > 0 {
				if source[i] == '(' {
					depth++
				} else if source[i] == ')' {
					depth--
				} else if source[i] == '"' {
					_, newI, _ := skipString(source, i)
					i = newI
					continue
				}
				i++
			}
		} else {
			break
		}
	}
	return i
}

func skipString(source string, pos int) (string, int, error) {
	if pos >= len(source) || source[pos] != '"' {
		return "", pos, fmt.Errorf("expected '\"' at position %d", pos)
	}
	i := pos + 1
	var sb strings.Builder
	for i < len(source) {
		if source[i] == '\\' && i+1 < len(source) {
			sb.WriteByte(source[i+1])
			i += 2
		} else if source[i] == '"' {
			i++
			return sb.String(), i, nil
		} else {
			sb.WriteByte(source[i])
			i++
		}
	}
	return "", i, fmt.Errorf("unterminated string at position %d", pos)
}

func skipWS(source string, pos int) int {
	for pos < len(source) && (source[pos] == ' ' || source[pos] == '\t' || source[pos] == '\n' || source[pos] == '\r') {
		pos++
	}
	return pos
}

func isIdentStart(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '.' || c == '-'
}

// captureToFieldName converts a capture name to a Go PascalCase field name.
// Examples: "name" → "Name", "function.name" → "FunctionName"
func captureToFieldName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '.' || r == '-' || r == '_'
	})
	var sb strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			sb.WriteString(string(runes))
		}
	}
	return sb.String()
}

// toPascalCase converts a snake_case or kebab-case string to PascalCase.
func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})
	var sb strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			sb.WriteString(string(runes))
		}
	}
	return sb.String()
}

// patternStructName generates a unique struct name for a pattern.
func patternStructName(p PatternInfo, index int, queryTypeName string, used map[string]int) string {
	var base string
	if p.RootNodeType != "" {
		base = toPascalCase(p.RootNodeType) + "Match"
	} else {
		base = fmt.Sprintf("%sPattern%dMatch", queryTypeName, index)
	}
	count := used[base]
	used[base]++
	if count > 0 {
		return fmt.Sprintf("%s%d", base, count)
	}
	return base
}

// goStringLiteral returns a Go source string literal.
func goStringLiteral(s string) string {
	// Use backtick if no backticks in string.
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	// Fall back to quoted string.
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
