// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "commonlisp",
		Extensions:         []string{".cl", ".lisp", ".lsp"},
		Language:           CommonlispLanguage,
		HighlightQuery:     commonlispHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("commonlisp"),
	})
}

const commonlispHighlightQuery = "(sym_lit) @symbol\n"
