// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "markdown_inline",
		Extensions:         nil,
		Language:           MarkdownInlineLanguage,
		HighlightQuery:     markdownInlineHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("markdown_inline"),
	})
}

const markdownInlineHighlightQuery = "((emphasis\n  (strong_emphasis)) @markup.strong)\n\n((strong_emphasis) @markup.strong\n  (#not-has-parent? @markup.strong emphasis))\n"
