// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "promql",
		Extensions:     []string{".promql"},
		Language:       PromqlLanguage,
		HighlightQuery: promqlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("promql"),
	})
}

const promqlHighlightQuery = "(metric_name) @function\n\n(label_name) @property\n(label_value) @string\n\n\"=\" @operator\n\n\"{\" @punctuation.bracket\n\"}\" @punctuation.bracket\n"
