// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "wat",
		Extensions:         []string{".wat", ".wast"},
		Language:           WatLanguage,
		HighlightQuery:     watHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("wat"),
	})
}

const watHighlightQuery = "(identifier) @variable\n(op_nullary) @function\n"
